---
# =============================================================================
# Ansible Inventory — auto-generated by Terraform
# =============================================================================
# DO NOT EDIT MANUALLY — file này được tạo tự động sau mỗi lần terraform apply.
# Source: iac/terraform/templates/inventory.yml.tpl
# =============================================================================

all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    # =====================================================================
    # NHÓM 1: Public DMZ — Internet-facing
    # =====================================================================

    # --- Nginx Reverse Proxy (load-balancer-server) ---
    load_balancers:
      hosts:
        load-balancer-server:
          ansible_host: ${lb_private_ip}
          public_ip: ${lb_public_ip}

    # --- Teleport Access Management ---
    teleport:
      hosts:
        teleport:
          ansible_host: ${teleport_private_ip}
          public_ip: ${teleport_public_ip}

    # --- Kong API Gateway ---
    kong_gateway:
      hosts:
        kong-gateway:
          ansible_host: ${kong_private_ip}
          public_ip: ${kong_public_ip}

    # =====================================================================
    # NHÓM 2: Platform Tools — Internal Services (Private Subnet)
    # =====================================================================

    # --- GitLab, Harbor, SonarQube, Rancher, Dev-Server ---
    platform_tools:
      hosts:
        gitlab-server:
          ansible_host: ${platform_tools["gitlab-server"]}
        harbor-server:
          ansible_host: ${platform_tools["harbor-server"]}
        sonarqube-server:
          ansible_host: ${platform_tools["sonarqube-server"]}
        rancher-server:
          ansible_host: ${platform_tools["rancher-server"]}
        dev-server:
          ansible_host: ${platform_tools["dev-server"]}

    # --- ELK Stack (Elasticsearch + Logstash + Kibana) ---
    elk:
      hosts:
        elk:
          ansible_host: ${elk_private_ip}

    # =====================================================================
    # NHÓM 3: Kubernetes HA Control-Plane (v1.30)
    # =====================================================================
    k8s_masters:
      hosts:
        k8s-master-1:
          ansible_host: ${k8s_masters["k8s-master-1"]}
        k8s-master-2:
          ansible_host: ${k8s_masters["k8s-master-2"]}
        k8s-master-3:
          ansible_host: ${k8s_masters["k8s-master-3"]}

    # =====================================================================
    # NHÓM 4: Kubernetes Worker Nodes — chạy application pods (ShopNow...)
    # =====================================================================
    k8s_workers:
      hosts:
        k8s-worker-1:
          ansible_host: ${k8s_workers["k8s-worker-1"]}
        k8s-worker-2:
          ansible_host: ${k8s_workers["k8s-worker-2"]}
        k8s-worker-3:
          ansible_host: ${k8s_workers["k8s-worker-3"]}

    # =====================================================================
    # NHÓM 5: Storage HA Cluster — GlusterFS Replicated Volume
    # =====================================================================
    storage_nodes:
      hosts:
        storage-master-1:
          ansible_host: ${storage_nodes["storage-master-1"]}
        storage-master-2:
          ansible_host: ${storage_nodes["storage-master-2"]}
        storage-master-3:
          ansible_host: ${storage_nodes["storage-master-3"]}
